### PR TITLE
[Fix #143] Fix an error for `Minitest/LiteralAsActualArgumentTest`

### LINKED ISSUE #143: `Minitest/LiteralAsActualArgument` infinitely loops when both args are literals.
I ran across a piece of code in which someone was trying to assert that a block would never be called. It looks like they didn't know about `#flunk`, so they used this instead:

```ruby
assert_equal 0, 1, "This block should not have run"
```

While this is odd code that should be fixed, it shouldn't crash the cop.

--------

## Expected behavior

Several behaviours seem reasonable to me:
1. Do nothing
2. Swap the two literals
3. Ideally, compare the two literals for equality and either:
  * Suggest to use `flunk` if they're unequal
  * Delete the assertion if they're equal

## Actual behavior

```shell
Infinite loop detected in .../file.rb and caused by Minitest/LiteralAsActualArgument -> Minitest/LiteralAsActualArgument
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:298:in `check_for_infinite_loop'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:281:in `block in iterate_until_no_changes'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:280:in `loop'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:280:in `iterate_until_no_changes'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:249:in `do_inspection_loop'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:130:in `block in file_offenses'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:155:in `file_offense_cache'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:129:in `file_offenses'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:120:in `process_file'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:100:in `each'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:100:in `reduce'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/runner.rb:47:in `run'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli/command.rb:11:in `run'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli/environment.rb:18:in `run'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli.rb:71:in `run_command'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli.rb:78:in `execute_runners'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/lib/rubocop/cli.rb:47:in `run'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/exe/rubocop:12:in `block in <top (required)>'
/opt/rubies/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/Users/Alex/.gem/ruby/2.7.2/gems/rubocop-1.21.0/exe/rubocop:12:in `<top (required)>'
/Users/Alex/.gem/ruby/2.7.2/bin/rubocop:23:in `load'
/Users/Alex/.gem/ruby/2.7.2/bin/rubocop:23:in `<main>'
```

## Steps to reproduce the problem

On a file that contains an assertion with two literal args (like shown above), run:

```sh
rubocop --auto-correct-all --only Minitest/LiteralAsActualArgument
```

## RuboCop version

```
$ [bundle exec] rubocop -V
1.21.0 (using Parser 3.0.2.0, rubocop-ast 1.11.0, running on ruby 2.7.2 x86_64-darwin20)
  - rubocop-minitest 0.15.0
  - rubocop-rails 2.11.3
  - rubocop-sorbet 0.6.2
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #143.

This PR fixes an error for `Minitest/LiteralAsActualArgumentTest` when expected and actual arguments are literals.

-----------------

Before submitting the PR make sure the following are checked:

* [x] Wrote [good commit messages][1].
* [x] Commit message starts with `[Fix #issue-number]` (if the related issue exists).
* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [Changelog](https://github.com/rubocop-hq/rubocop-minitest/blob/master/CHANGELOG.md) if the new code introduces user-observable changes. See [changelog entry format](https://github.com/rubocop-hq/rubocop-minitest/blob/master/CONTRIBUTING.md#changelog-entry-format).
* [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.
* [x] Run `bundle exec rake default`. It executes all tests and RuboCop for itself, and generates the documentation.

[1]: https://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: test/rubocop/cop/minitest/literal_as_actual_argument_test.rb [hunk 1]
```diff
@@ -99,4 +99,14 @@ def test_do_something
       end
     RUBY
   end
+
+  def test_registers_offense_when_expected_and_actual_are_basic_literals
```
Comment (andyw8) [inline test/rubocop/cop/minitest/literal_as_actual_argument_test.rb:103]:
```suggestion
  def test_does_not_register_offense_when_expected_and_actual_are_basic_literals
```
